<a href="https://colab.research.google.com/github/Jyothika1415/P2-Recommendationsystems/blob/main/IMDP__Movie_Recommendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data collection and preprocessing

In [ ]:
movies_data = pd.read_csv('/content/movieMetadata (1).csv')

In [ ]:
movies_data.head()

Movie Title  \
0             The Shawshank Redemption   
1                        The Godfather   
2  Ramayana: The Legend of Prince Rama   
3                       Hababam Sinifi   
4                      The Dark Knight   

                                         Description  \
0  Over the course of several years, two convicts...   
1  Don Vito Corleone, head of a mafia family, dec...   
2  An anime adaptation of the Hindu epic the Rama...   
3  Lazy, uneducated students share a very close b...   
4  When the menace known as the Joker wreaks havo...   

                        Genre  Rating Metascore Gross_Income      Votes  \
0                       Drama     9.3        82      $28.34M  2,806,728   
1                 Crime,Drama     9.2       100     $134.97M  1,955,879   
2  Animation,Action,Adventure     9.2      $$$$         none     13,028   
3                Comedy,Drama     9.2      $$$$         none     42,246   
4          Action,Crime,Drama     9.0        84     $534.86M  2,788,482   

   Runtime Certificate  Year                                       Director  \
0      142           A  1994                                 Frank Darabont   
1      175           A  1972                           Francis Ford Coppola   
2      135           U  1993  Directors:Ram Mohan,Yûgô Sakô,Koichi Saski   
3       87        none  1975                                  Ertem Egilmez   
4      152          UA  2008                              Christopher Nolan   

                                               Stars  
0  Tim Robbins,Morgan Freeman,Bob Gunton,William ...  
1    Marlon Brando,Al Pacino,James Caan,Diane Keaton  
2  Arun Govil,Nikhil Kapoor,Edie Mirman,Rael Pada...  
3  Kemal Sunal,Münir Özkul,Halit Akçatepe,Tari...  
4  Christian Bale,Heath Ledger,Aaron Eckhart,Mich...

In [ ]:
# find the rows and columns in tje data feame
movies_data.shape

(10100, 12)

In [ ]:
movies_data.reset_index(inplace=True)

In [ ]:
movies_data.head()

index                          Movie Title  \
0      0             The Shawshank Redemption   
1      1                        The Godfather   
2      2  Ramayana: The Legend of Prince Rama   
3      3                       Hababam Sinifi   
4      4                      The Dark Knight   

                                         Description  \
0  Over the course of several years, two convicts...   
1  Don Vito Corleone, head of a mafia family, dec...   
2  An anime adaptation of the Hindu epic the Rama...   
3  Lazy, uneducated students share a very close b...   
4  When the menace known as the Joker wreaks havo...   

                        Genre  Rating Metascore Gross_Income      Votes  \
0                       Drama     9.3        82      $28.34M  2,806,728   
1                 Crime,Drama     9.2       100     $134.97M  1,955,879   
2  Animation,Action,Adventure     9.2      $$$$         none     13,028   
3                Comedy,Drama     9.2      $$$$         none     42,246   
4          Action,Crime,Drama     9.0        84     $534.86M  2,788,482   

   Runtime Certificate  Year                                       Director  \
0      142           A  1994                                 Frank Darabont   
1      175           A  1972                           Francis Ford Coppola   
2      135           U  1993  Directors:Ram Mohan,Yûgô Sakô,Koichi Saski   
3       87        none  1975                                  Ertem Egilmez   
4      152          UA  2008                              Christopher Nolan   

                                               Stars  
0  Tim Robbins,Morgan Freeman,Bob Gunton,William ...  
1    Marlon Brando,Al Pacino,James Caan,Diane Keaton  
2  Arun Govil,Nikhil Kapoor,Edie Mirman,Rael Pada...  
3  Kemal Sunal,Münir Özkul,Halit Akçatepe,Tari...  
4  Christian Bale,Heath Ledger,Aaron Eckhart,Mich...

In [ ]:
movies_data.shape

(10100, 13)

In [ ]:
# selecting the relevent features of the recomandation
selected_features = ['Description','Genre','Certificate','Director','Stars']
print(selected_features)

['Description', 'Genre', 'Certificate', 'Director', 'Stars']


In [ ]:
# replacing the null values with null string
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')


In [ ]:
# combining all the 5 seleted features
combined_features = movies_data['Description']+' '+movies_data['Genre']+' '+movies_data['Certificate']+' '+movies_data['Director']+' '+movies_data['Stars']
print(combined_features)

0        Over the course of several years, two convicts...
1        Don Vito Corleone, head of a mafia family, dec...
2        An anime adaptation of the Hindu epic the Rama...
3        Lazy, uneducated students share a very close b...
4        When the menace known as the Joker wreaks havo...
                               ...                        
10095    A young pickpocket and an unruly CIA agent tea...
10096    It's the wedding of Jim and Michelle and the g...
10097    The recovery of a microchip off the body of a ...
10098    Count Dracula and company participate in a cru...
10099    Newlywed couple Ted and Tami-Lynn want to have...
Length: 10100, dtype: object


In [ ]:
# converting the text data to feature vectors
vectorizer = TfidfVectorizer()

In [ ]:
feature_vectorizer = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectorizer)

  (0, 27255)	0.24246626071339844
  (0, 34115)	0.14962861701209465
  (0, 13229)	0.2593609349166349
  (0, 3975)	0.17418085285267268
  (0, 11693)	0.18460940908409004
  (0, 21209)	0.17664052072673783
  (0, 26698)	0.19967321649087438
  (0, 31573)	0.1593748992055757
  (0, 7709)	0.2551754358062899
  (0, 11632)	0.15974584652350135
  (0, 9153)	0.0477288607777858
  (0, 6572)	0.2551754358062899
  (0, 3028)	0.24519360470211915
  (0, 31472)	0.1483058602977063
  (0, 25855)	0.20717179514772044
  (0, 10401)	0.20472811538037047
  (0, 1471)	0.05138281119738658
  (0, 6790)	0.26990755035555214
  (0, 28068)	0.20552169403413395
  (0, 11757)	0.17301980595113922
  (0, 11517)	0.18339591499026778
  (0, 6899)	0.23344895748122932
  (0, 32367)	0.10914961996226126
  (0, 34555)	0.1358568085444666
  (0, 28325)	0.18630412897038598
  :	:
  (10099, 33680)	0.16012370370020446
  (10099, 22085)	0.1910670490248666
  (10099, 19019)	0.16012370370020446
  (10099, 24962)	0.1497196974891111
  (10099, 2592)	0.1548484063741155
  (

Cosine Similarity

In [ ]:
# getting the similarity scores using cosine similarity
similarity = cosine_similarity(feature_vectorizer)

In [ ]:
print(similarity)

[[1.         0.0270256  0.00634464 ... 0.00707199 0.00393683 0.0041155 ]
 [0.0270256  1.         0.00719338 ... 0.02530017 0.02195585 0.02011602]
 [0.00634464 0.00719338 1.         ... 0.01797261 0.01942505 0.00156348]
 ...
 [0.00707199 0.02530017 0.01797261 ... 1.         0.02295195 0.01432523]
 [0.00393683 0.02195585 0.01942505 ... 0.02295195 1.         0.00903787]
 [0.0041155  0.02011602 0.00156348 ... 0.01432523 0.00903787 1.        ]]


In [ ]:
print(similarity.shape)

(10100, 10100)


In [ ]:
movieSimilarity = pd.DataFrame(similarity, columns= movies_data['Movie Title'], index=movies_data['Movie Title']) # convert to dataframe
movieSimilarity.head()

Movie Title                          The Shawshank Redemption  The Godfather  \
Movie Title                                                                    
The Shawshank Redemption                             1.000000       0.027026   
The Godfather                                        0.027026       1.000000   
Ramayana: The Legend of Prince Rama                  0.006345       0.007193   
Hababam Sinifi                                       0.006481       0.012280   
The Dark Knight                                      0.019887       0.049138   

Movie Title                          Ramayana: The Legend of Prince Rama  \
Movie Title                                                                
The Shawshank Redemption                                        0.006345   
The Godfather                                                   0.007193   
Ramayana: The Legend of Prince Rama                             1.000000   
Hababam Sinifi                                                  0.017634   
The Dark Knight                                                 0.024066   

Movie Title                          Hababam Sinifi  The Dark Knight  \
Movie Title                                                            
The Shawshank Redemption                   0.006481         0.019887   
The Godfather                              0.012280         0.049138   
Ramayana: The Legend of Prince Rama        0.017634         0.024066   
Hababam Sinifi                             1.000000         0.023631   
The Dark Knight                            0.023631         1.000000   

Movie Title                          Schindler's List  \
Movie Title                                             
The Shawshank Redemption                     0.003672   
The Godfather                                0.018881   
Ramayana: The Legend of Prince Rama          0.003840   
Hababam Sinifi                               0.021531   
The Dark Knight                              0.010864   

Movie Title                          The Lord of the Rings: The Return of the King  \
Movie Title                                                                          
The Shawshank Redemption                                                  0.012544   
The Godfather                                                             0.025726   
Ramayana: The Legend of Prince Rama                                       0.018700   
Hababam Sinifi                                                            0.025865   
The Dark Knight                                                           0.055879   

Movie Title                          12 Angry Men  The Godfather Part II  \
Movie Title                                                                
The Shawshank Redemption                 0.005159               0.012894   
The Godfather                            0.018073               0.375800   
Ramayana: The Legend of Prince Rama      0.007422               0.009913   
Hababam Sinifi                           0.018765               0.019114   
The Dark Knight                          0.020868               0.061250   

Movie Title                          Aynabaji  ...  \
Movie Title                                    ...   
The Shawshank Redemption             0.000000  ...   
The Godfather                        0.032473  ...   
Ramayana: The Legend of Prince Rama  0.000000  ...   
Hababam Sinifi                       0.008245  ...   
The Dark Knight                      0.030562  ...   

Movie Title                          Terminator 3: Rise of the Machines  \
Movie Title                                                               
The Shawshank Redemption                                       0.002328   
The Godfather                                                  0.009287   
Ramayana: The Legend of Prince Rama                            0.007565   
Hababam Sinifi                                                 0.020738   
The Dark Knight                     

In [ ]:
# getting the movie name the user
movie_name = input('Enter your favorite movie name: ')

Enter your favorite movie name: iron nan


In [ ]:
# ctreating a list with all the movie names given in the dataset
list_of_all_titles =movies_data['Movie Title'].tolist()
print(list_of_all_titles)

['The Shawshank Redemption', 'The Godfather', 'Ramayana: The Legend of Prince Rama', 'Hababam Sinifi', 'The Dark Knight', "Schindler's List", 'The Lord of the Rings: The Return of the King', '12 Angry Men', 'The Godfather Part II', 'Aynabaji', 'DAMaN', 'Pulp Fiction', 'Kimetsu no Yaiba: Tsuzumi Yashiki Hen', 'Al-risâlah', 'Tosun Pasa', 'Hababam Sinifi Sinifta Kaldi', 'Fight Club', 'The Lord of the Rings: The Fellowship of the Ring', 'Inception', 'Forrest Gump', 'The Lord of the Rings: The Two Towers', 'Il buono, il brutto, il cattivo', 'Jai Bhim', 'Kill Bill: The Whole Bloody Affair', '777 Charlie', 'Manichitrathazhu', 'Kimetsu no Yaiba: Natagumo Yama Hen', 'Balkanski spijun', '#Home', 'Maratonci trce pocasni krug', 'Süt Kardesler', 'Spider-Man: Across the Spider-Verse', 'Interstellar', 'Goodfellas', 'The Matrix', "One Flew Over the Cuckoo's Nest", 'Star Wars: Episode V - The Empire Strikes Back', 'The Legend of Maula Jatt', 'Rocketry: The Nambi Effect', 'Toma', 'Soorarai Pottru', 'P

In [ ]:
# finding the close match for the movie name given by the user
find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)

In [ ]:
print(find_close_match)

['Iron Man', 'Iron Man 2', 'Gridiron Gang']


In [ ]:
close_match = find_close_match[0]
print(close_match )

Iron Man


In [ ]:
# finding the index of the movie with title
index_of_the_movie = movies_data[movies_data['Movie Title'] == close_match]['index'].values[0]
print(index_of_the_movie)

687


In [ ]:
# getting a list of similar movies
similarity_score = list(enumerate(similarity[index_of_the_movie]))

In [ ]:
print(similarity_score)

[(0, 0.0022887447437739527), (1, 0.009875405455418916), (2, 0.014473838607611348), (3, 0.0053753422203592065), (4, 0.03900447703414061), (5, 0.009888256231023424), (6, 0.014288883119917278), (7, 0.005835216954623296), (8, 0.028867962982810844), (9, 0.004838441378756343), (10, 0.016122165869767544), (11, 0.009679781971745498), (12, 0.010190907715916202), (13, 0.01596780398587724), (14, 0.0), (15, 0.00871603824407062), (16, 0.029405630493727103), (17, 0.0127688357926729), (18, 0.04678054364814574), (19, 0.037942797594320316), (20, 0.022659759259017632), (21, 0.022076681908108426), (22, 0.0059502134140675695), (23, 0.007622172629771957), (24, 0.018576766191861147), (25, 0.010261777980436806), (26, 0.02626096191682888), (27, 0.00907446910784564), (28, 0.0032286946935982793), (29, 0.02186977471732139), (30, 0.006257814968006177), (31, 0.012288633648000306), (32, 0.04321735276990375), (33, 0.01754289663757852), (34, 0.04913583646991721), (35, 0.006241563004955023), (36, 0.022929640432007382)

In [ ]:
len(similarity_score)

10100

In [ ]:
# sorting the movies based on there similarity score
sorted_similar_movies = sorted(similarity_score, key = lambda X:X[1],reverse=True)

In [ ]:
print(sorted_similar_movies)

[(687, 0.9999999999999999), (4204, 0.2952232678301247), (3343, 0.26754440355941816), (2530, 0.1925063704184555), (2481, 0.1409848072324102), (6165, 0.13025073535081547), (4007, 0.12407189569899568), (2103, 0.12243773926641568), (512, 0.12013932244962425), (9745, 0.11842687139824123), (118, 0.11285417248718947), (6614, 0.11079769694298469), (4419, 0.1083239723199792), (7050, 0.10815349311011888), (924, 0.10675614213883465), (6959, 0.10579315200903944), (6381, 0.10553170723318638), (3384, 0.10519077949191026), (3761, 0.1028577838599015), (8233, 0.10195775184511499), (6349, 0.10005609561273614), (68, 0.09932010503088506), (7203, 0.09793395209659123), (3320, 0.09771856616736477), (7852, 0.09757787262840167), (4578, 0.09709254763090978), (6850, 0.09603879184034213), (2477, 0.0957633284343846), (8673, 0.09540268319027063), (5897, 0.09523753371138209), (4394, 0.0946728205746485), (7771, 0.09391569614609134), (1798, 0.09339669956906123), (4550, 0.09328922799979522), (2155, 0.09297790201969774)

In [ ]:
# print the name of similar movies based on the index
print('Movies suggested for you \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index == index]['Movie Title'].values[0]
  if(i<40):
    print(i,'.',title_from_index)
    i += 1

Movies suggested for you 

1 . Iron Man
2 . Iron Man 2
3 . Iron Man Three
4 . Chef
5 . Avengers: Age of Ultron
6 . Made
7 . The Vikings
8 . Spider-Man: Homecoming
9 . The Avengers
10 . Bad Samaritan
11 . Avengers: Infinity War
12 . Blue Beetle
13 . Charlie Bartlett
14 . Sabotage
15 . Captain America: Civil War
16 . The Clearing
17 . Blown Away
18 . Deja Vu
19 . Transformers
20 . Sanctum
21 . Time Trap
22 . Oppenheimer
23 . Dolittle
24 . Tropic Thunder
25 . Cowboys
26 . Tron: Legacy
27 . Tau
28 . The Shape of Water
29 . View from the Top
30 . Rambo: First Blood Part II
31 . The Emerald Forest
32 . Brake
33 . Kiss Kiss Bang Bang
34 . The Lion King
35 . Sherlock Holmes: A Game of Shadows
36 . Donnie Darko
37 . Sky Captain and the World of Tomorrow
38 . Tron
39 . The Gingerbread Man


Movie Recomandation System

In [ ]:
# Predictive system
movie_name = input('Enter your favorite movie name: ')
list_of_all_titles =movies_data['Movie Title'].tolist()
find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)
close_match = find_close_match[0]
index_of_the_movie = movies_data[movies_data['Movie Title'] == close_match]['index'].values[0]
similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda X:X[1],reverse=True)

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index == index]['Movie Title'].values[0]
  if(i<40):
    print(i,'.',title_from_index)
    i += 1



Enter your favorite movie name:  avatar
Movies suggested for you : 

1 . Avatar
2 . Avatar: The Way of Water
3 . The Book of Life
4 . Terminator Salvation
5 . Guardians of the Galaxy
6 . Guardians of the Galaxy Vol. 2
7 . Aliens
8 . Lara Croft: Tomb Raider - The Cradle of Life
9 . Ghostbusters
10 . Invictus
11 . Snow White: A Tale of Terror
12 . I Kill Giants
13 . Ferdinand
14 . Snow Cake
15 . Oz the Great and Powerful
16 . Star Trek Into Darkness
17 . Chappie
18 . The Fast and the Furious
19 . Jarhead
20 . The Losers
21 . Star Trek Beyond
22 . Billy Elliot
23 . 1492: Conquest of Paradise
24 . Brothers
25 . The Words
26 . The Village
27 . Out of the Furnace
28 . Machete
29 . Colombiana
30 . Black Adam
31 . Rampart
32 . Guess Who
33 . Clash of the Titans
34 . Tron: Legacy
35 . Ghostbusters II
36 . Pride and Prejudice and Zombies
37 . Hanna
38 . I Am Wrath
39 . First Man
